---
fixtures:
  repositories:
    concat:
      # master is at 4.0.1, but we are bound to < 4.0.0 in our metadata.json
      repo: https://github.com/simp/puppetlabs-concat
      ref: 3.0.0
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
  symlinks:
    sudo: "#{source_dir}"
