---
fixtures:
  repositories:
    concat: https://github.com/simp/puppetlabs-concat
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
  symlinks:
    sudo: "#{source_dir}"
